name: Publish Snapshot

# on:
#   schedule:
#     - cron:  '0 0 * * *'
on:
  pull_request:
    branches:
    - master

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Release Maven package
      env:
        ASF_USERNAME: ${{ secrets.NEXUS_USER }}
        ASF_PASSWORD: ${{ secrets.NEXUS_PW }}
        GPG_KEY: "not_used"
        GPG_PASSPHRASE: "not_used"
      run: ./dev/create-release/release-build.sh publish-snapshot
